lab_1/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_4/urls.py
from django.conf.urls import url
from .views import index, message_post, message_table

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_message', message_post, name='add_message'),
    url(r'^result_table', message_table, name='result_table'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1, namespace='lab-1')),
    url(r'^lab-2/', include(lab_2, namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3, namespace='lab-3')),
    # url(r'^$', RedirectView.as_view(permanent= True, url='/lab-2/'), name='index'),
    url(r'^$', RedirectView.as_view(permanent=True, url='/lab-4/'), name='index'),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    # url(r'^$', index_lab2, name='index'),
]

lab_4/models.py
from django.db import models
from django.utils import timezone

class Message(models.Model):
    def convertTZ():
        return timezone.now() + timezone.timedelta(hours=7)

    name = models.CharField(max_length=27)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(default=convertTZ)

    def __str__(self):
        return self.message

lab_4/forms.py
from django import forms

class Message_Form(forms.Form):
    lab_4_error_messages = {
        'required': 'Tolong isi input ini ya teman :)',
        'invalid': 'Isi input dengan email ya teman :)',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True, error_messages=lab_4_error_messages)

lab_4/views.py
from django.shortcuts import render
from lab_2.views import landing_page_content
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message

response = {'author': "Arga Ghulam Ahmad"}
about_me = ["# Computer Science Student", "# Full Time Programmer", "# Part Time Gamer", "# Muslim", "# Bike Rider", "# OmegaCSUI"]
def index(request):
    response['content'] = landing_page_content
    response['about_me'] = about_me
    response['message_form'] = Message_Form
    if 'user_login' in request.session:
        html = 'lab_4/lab_4.html'
        response['user_name'] = request.session['user_login']
        response['user_npm'] = request.session['kode_identitas']
        response['author'] = "Arga Ghulam Ahmad"
        response['button_logout_session'] = True
        return render(request, html, response)
    else:
        html = 'lab_9/session/login.html'
        return render(request, html, response)

def message_post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(name=response['name'], email=response['email'],
                          message=response['message'])
        message.save()
        html ='lab_4/form_result.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/lab-4/')

def message_table(request):
    if 'user_login' in request.session:
        response['user_name'] = request.session['user_login']
        response['user_npm'] = request.session['kode_identitas']
        response['author'] = "Arga Ghulam Ahmad"
        response['button_logout_session'] = True
        message = Message.objects.all()
        response['message'] = message
        html = 'lab_4/table.html'
        return render(request, html, response)
    else:
        html = 'lab_9/session/login.html'
        return render(request, html, response)

lab_4/templates/lab_4/form_result.html
 {% extends "lab_4/layout/base.html" %}
    {% block title %} Pesan dari {{ name }} {% endblock %}
    {% block content %}
    <textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;-{{name}} 
        by {{ email }}
    </textarea>

{#    {% include "lab_4/partials/footer.html" %}#}
    {% endblock %}

{#    {% block footer %}#}
{#        <p> &copy; {{name}} </p>#}
{#    {% endblock %}#}

lab_4/templates/lab_4/lab_4.html
{% extends "lab_4/layout/base.html" %}

    {% block content %}
        <style>
            #profile-photo {
                display: block;
                margin-right: auto;
                margin-left: auto;
                padding: 20px 10px 20px 10px;
                border-radius: 50%;
            }
            #description-bio {
                text-align: center;
                width: 60%;
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
            .footer-social-icons {
                text-align: center;
                padding-top: 10px;
                padding-bottom: 10px;
            }
            #title-portopolio {
                text-align: center;
                margin-left: auto;
                margin-right: auto;
                visibility: hidden;
            }

            ul#horizontal-list {
                min-width: 696px;
                list-style: none;
                padding-top: 20px;
            }
            ul#horizontal-list li {
                display: inline;
                font-size: x-small;
            }

            #about_me_list {
                visibility: visible;
                display: block;
                margin-right: auto;
                margin-left: auto;
                text-align: center;
            }

            #form-sec {
                display: block;
                margin: 0 auto 0 auto;
                width: 70%;
            }
        </style>

        {#<h1 id="title-portopolio">Portofolio</h1>#}
        <div>
            <img id="profile-photo" src="https://avatars0.githubusercontent.com/u/19942092?v=4&s=460" alt="argaghulamahmad" />
            <h2 style="text-align: center;">Arga Ghulam Ahmad</h2>
            <div class="footer-social-icons">
              <a href="https://facebook.com/argaghulamahmad"><i class="fa fa-facebook"></i></a>
              <a href="https://twitter.com/ahmadghulamarga"><i class="fa fa-twitter"></i></a>
              <a href="https://instagram.com/argaghulamahmad"><i class="fa fa-instagram"></i></a>
              <a href="https://linkedin.com/in/argaghulamahmad"><i class="fa fa-linkedin"></i></a>
              <a href="https://github.com/argaghulamahmad"><i class="fa fa-github"></i></a>
              <a href="https://gitlab.com/argaghulamahmad"><i class="fa fa-gitlab"></i></a>
              <a href="https://behance.net/argaghulamahmad"><i class="fa fa-behance"></i></a>
              <a href="https://blog.arga.ga"><i class="fa fa-rss"></i></a>
            </div>
            {#<h2 style="visibility: hidden">Bio</h2>#}
            <p id="description-bio">Hello, this is {{ author }}. {{ content }}.</p>
        </div>
        <section name="about_me" id="about_me_list">
        {#<h2>List</h2>#}
            <ul id="horizontal-list">
                {% for ii in about_me %}
                <li> {{ ii }} </li>
                {% endfor %}
            </ul>
        </section>
        <hr/>
            <section name="form" id="form-sec">
            <h2>Send Message</h2>
            <form id="form" method="POST" action="{% url 'lab-4:add_message' %}">
                {% csrf_token %}
                {{ message_form }}
                <br>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </section>

    {% endblock %}

lab_4/templates/lab_4/table.html
 {% extends "lab_4/layout/base.html" %}

    {% block title %} Kumpulan Pesan {% endblock %}

    {% block content %}
    <!--  Populate semua isi pesan dari model -->
    <table class="table">
        <thead>
            <th>Nama</th>
            <th>Email</th>
            <th>Pesan</th>
            <th>Dibuat Pada</th>
        </thead>
        <tbody>
            <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
            {% for i in message %}
            {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
            <tr class="warning"> {% else %} <tr class="success">
                {% endif %}
                <td> {{i.name}} </td>
                <td> {{i.email}} </td>
                <td> {{i.message}} </td>
                <td> {{i.created_date.time}} </td>
            </tr>             
            {% endfor %}
        </tbody>
    </table>

    {% endblock %}