lab_1/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, get_friend_list_objects_json, friend_description

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-friend/$', add_friend, name='add-friend'),
    url(r'^validate-npm/$', validate_npm, name='validate-npm'),
    # url(r'^delete-friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete-friend'),
    url(r'^delete-friend/$', delete_friend, name='delete-friend'),
    url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
    url(r'^get-friend-list-json/$', get_friend_list_objects_json, name='get-friend-list-json'),
    url(r'^friend-description/(?P<index>\d+)/$', friend_description, name='friend-description'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1, namespace='lab-1')),
    url(r'^lab-2/', include(lab_2, namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3, namespace='lab-3')),
    # url(r'^$', RedirectView.as_view(permanent= True, url='/lab-2/'), name='index'),
    url(r'^$', RedirectView.as_view(permanent=True, url='/lab-4/'), name='index'),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    # url(r'^$', index_lab2, name='index'),
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    added_at = models.DateField(auto_now_add=True)

lab_7/views.py
import datetime
import json

import environ
from django.core import serializers
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from .models import Friend

response = {}

from lab_9.csui_helper import *


now = datetime.datetime.now()
root = environ.Path(__file__) - 3 # three folder back (/a/b/c/ - 3 = /)
env = environ.Env(DEBUG=(bool, False),)
environ.Env.read_env('.env')

@csrf_exempt
def index(request):
    response = {}
    if 'user_login' in request.session:
        response['user_name'] = request.session['user_login']
        response['user_npm'] = request.session['kode_identitas']
        response['author'] = "Arga Ghulam Ahmad"
        response['button_logout_session'] = True

        access_token = request.session['access_token']
        mahasiswa_list = get_mahasiswa_list(access_token)
        friend_list = Friend.objects.all()
        page = request.GET.get('page', 1)
        paginator = Paginator(mahasiswa_list, 10)
        mahasiswa_list = paginator.page(page)
        response['mahasiswa_list'] = mahasiswa_list
        response['friend_list'] = friend_list
        html = 'lab_7/lab_7.html'
        return render(request, html, response)
    else:
        html = 'lab_9/session/login.html'
        return render(request, html, response)

def friend_description(request, index):
    username = env("SSO_USERNAME")
    password = env("SSO_PASSWORD")

    index_number = int(index)
    siakng_mahasiswalist_data = get_mahasiswa_list(get_access_token(username, password))
    npm_mahasiswa = siakng_mahasiswalist_data[index_number]['npm']
    nama_mahasiswa = siakng_mahasiswalist_data[index_number]['nama']
    alamat_mahasiswa = siakng_mahasiswalist_data[index_number]['alamat_mhs']
    response = {
        "npm": npm_mahasiswa, "nama": nama_mahasiswa, "alamat": alamat_mahasiswa, "author": "Arga Ghulam Ahmad"
    }
    html = 'lab_7/deskripsi_teman.html'
    return render(request, html, response)


def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    response['author'] = "Arga Ghulam Ahmad"
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)


def get_friend_list_objects_json(request):
    friends_json = serializers.serialize("json", Friend.objects.all())
    data = {
        'friends_json': friends_json,
        'status': 'success'
    }
    return JsonResponse(data)


@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST.get('name', None)
        npm = request.POST.get('npm', None)
        friend_list = Friend.objects.all()
        is_taken = False
        for friend in friend_list:
            if friend.npm == npm:
                is_taken = True
        if not is_taken:
            friend = Friend(friend_name=name, npm=npm)
            friend.save()
            data = model_to_dict(friend)
            return HttpResponse(data)
        if is_taken:
            data = {}
            return HttpResponse(data)


@csrf_exempt
def delete_friend(request):
    if request.method == 'POST':
        friend_id = request.POST.get('friend_id', None)
        Friend.objects.filter(id=friend_id).delete()
        data = {
            'success': True,
            'friend_id': friend_id,
        }

        return JsonResponse(data)


@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    list_friends = Friend.objects.all()

    # lakukan pengecekan apakah Friend dgn npm tsb sudah ada
    taken = False
    for friend in list_friends:
        if friend.npm == npm:
            taken = True

    data = {
        'is_taken': taken
    }
    return JsonResponse(data)


def model_to_dict(obj):
    data = serializers.serialize('json', [obj, ])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <style>
        a.list-group-item {
            overflow: hidden;
        }

        a.list-group-item > div {
            vertical-align: middle;
        }
    </style>
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> Friend Fasilkom</h2>
                    <div id="friend-list-container" class="list-group">
                        {% comment %}{% if friend_list %}
                            {% for friend in friend_list %}
                                <a class="list-group-item">
                                    {{ friend.friend_name }}
                                    <span class="pull-right">
                                                 ({{ friend.npm }})
                                            </span>
                                </a>
                            {% endfor %}
                        {% else %}
                            <div class="alert alert-danger text-center">
                                <strong>Opps!</strong> Tidak ada teman
                            </div>
                        {% endif %}{% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $(document).ready(function () {
            getFriendList();
        });

        {# fungsi untuk menghapus teman pada database melalui button ber'id' delete_friend_button #}
        var deleteFriend = function (friend_id) {
            $.ajax({
                method: "POST",
                url: '{% url "lab-7:delete-friend" %}',
                data: {
                    'friend_id': friend_id
                },
                dataType: 'json',
                success: function (data) {
                    console.log(data.friend_id);
                    if (data.success) {
                        console.log(data.friend_id);
                        selectorToDelete = "[pk=" + data.friend_id + "]";
                        $(selectorToDelete).remove();
                    }
                    if ($("#friend-list-container").children().length === 0) {
                        $("#friend-list-container").append("<div class=\"alert alert-danger text-center\">" + "<strong>Opps!</strong> Tidak ada teman" + "</div>");
                    }
                }
            });
        };

        var getFriendList = function () {
            $.ajax({
                method: "GET",
                url: "{% url "lab-7:get-friend-list-json" %}",
                success: function (data) {
                    parsed_data = JSON.parse(data['friends_json']);
                    if (parsed_data.length === 0) {
                        $('#friend-list-container').append("<div class=\"alert alert-danger text-center\">" + "<strong>Opps!</strong> Tidak ada teman" + "</div>")
                    } else {
                        for (i = 0; i < parsed_data.length; i++) {
                            friend = parsed_data[i];
                            friend_name = friend["fields"]["friend_name"];
                            friend_npm = friend["fields"]["npm"];
                            friend_id = friend["pk"];
                            $('#friend-list-container').append(
                                "<a pk=\"" + friend_id + "\" class=\"list-group-item\">"
                                + friend_name
                                + "<span class=\"pull-right\">"
                                + "<button \" onClick=\"deleteFriend(" + friend_id + ")\" type=\"button\" class=\"btn btn-danger\" id=\"delete_friend_button\"> Delete </button>"
                                + "</span>"
                                + "<span class=\"pull-center\">" + " (" + friend_npm + ")" + "</span>"
                                + "</a>"
                            );
                        }
                    }
                },
                error: function (error) {
                    alert("Data json tidak valid!")
                }
            });
        };
    </script>
{% endblock %}

lab_7/templates/lab_7/deskripsi_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" class="friend-list">
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">Nama Mahasiswa</div>
                <div class="panel-body">
                    <h4>{{ nama }}</h4>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">NPM Mahasiswa</div>
                <div class="panel-body">
                    <h4>{{ npm }}</h4>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Alamat Mahasiswa</div>
                <div class="panel-body">
                    <h4 id="address">{{ alamat }}</h4>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">Map</div>
                <div class="panel-body">
                    <div id="googleMap" style="width:1100px; height:600px; margin: 50px 0"></div>
                </div>
            </div>
        </div>
        <div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        console.log($("#address").text());
        var address = $("#address").text();

        function initMap() {
            var geocoder = new google.maps.Geocoder();
            geocoder.geocode({'address': address}, function (results, status) {
                if (status === google.maps.GeocoderStatus.OK) {
                    var propertiPeta = {
                        center: results[0].geometry.location,
                        zoom: 15,
                        mapTypeId: google.maps.MapTypeId.ROADMAP
                    };
                    var peta = new google.maps.Map(document.getElementById("googleMap"), propertiPeta);
                    var marker = new google.maps.Marker({
                        map: peta,
                        position: results[0].geometry.location
                    });
                } else {
                    var html = '<div class="alert alert-danger text-center">' +
                        'Lokasi tidak ditemukan!' +
                        '</div>';
                    $("#googleMap").append(html)
                }
            });
        }
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
    <section name="mahasiswa-list" id="mahasiswa-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> Mahasiswa Fasilkom</h2>
                    <div class="list-group">
                        {% if mahasiswa_list %}
                            {% for mahasiswa in mahasiswa_list %}
                                <a class="list-group-item clearfix" id="mahasiswa-idx-{{ forloop.counter0 }}">
                                    <button type="button" class="btn btn-info"
                                            onClick="getFriendDescription({{ forloop.counter0 }})">{{ mahasiswa.nama }}
                                        ({{ mahasiswa.npm }})
                                    </button>
                                    <span class="pull-right">
                                    <span class="btn btn-md btn-success"
                                          onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                                        Tambah sebagai teman
                                    </span>
                                </span>
                                </a>
                            {% endfor %}
                        {% else %}
                            <div class="alert alert-danger text-center">
                                <strong>Opps!</strong> Tidak ada mahasiswa
                            </div>
                        {% endif %}
                    </div>
                    <ul class="pagination">
                        {% if mahasiswa_list.has_previous %}
                            <li><a href="?page={{ mahasiswa_list.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in mahasiswa_list.paginator.page_range %}
                            {% if mahasiswa_list.number == i %}
                                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if mahasiswa_list.has_next %}
                            <li><a href="?page={{ mahasiswa_list.next_page_number }}">&raquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>

                </div>
                <br>
                <div class="col-lg-4">
                    <h2> Teman Saya </h2>
                    <div class="list-group" id="friend-list">
                        {% if friend_list %}
                            {% for friend in friend_list %}
                                <a class="list-group-item clearfix">
                                    {{ friend.friend_name }} ({{ friend.npm }})
                                </a>
                            {% endfor %}
                        {% else %}
                            <div class="alert alert-danger text-center" id="msg-no-friend">
                                <strong>Opps!</strong> Tidak ada teman
                            </div>
                        {% endif %}
                    </div>
                    <form id="add-friend" action="#">
                        {% csrf_token %}
                        <label for="field_npm">npm</label>
                        <input id="field_npm" type="text" name="npm" class="form-control"/>
                        <label for="field_name">name</label>
                        <input id="field_name" type="text" name="name" class="form-control"/>
                        <button type="submit">Tambah</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $(document).ready(function () {
        });

        var addFriend = function (nama, npm) {
            $.ajax({
                method: "POST",
                url: "{% url "lab-7:add-friend" %}",
                data: {name: nama, npm: npm},
                success: function (data) {
                    {# hapus pesan tidak ada teman #}
                    $("#msg-no-friend").remove();

                    {# bila sudah ada npm tersebut dalam database friend  #}
                    if (data.length === 0) {
                        alert("Mahasiswa tersebut sudah ditambahkan sebagai teman");
                    }
                        {# bila belum ada nom tersebut dalam database friend #}
                    else {
                        obj_friend = JSON.parse(data);
                        html = '<a class="list-group-item clearfix">' +
                            obj_friend.friend_name + " (" + obj_friend.npm + ") " +
                            '</a>';
                        $("#friend-list").append(html);
                    }
                },
                error: function (error) {
                    alert("Mahasiswa tersebut sudah ditambahkan sebagai teman");
                }
            });
        };

        $("#add-friend").on("submit", function () {
            name = $("#field_name").val();
            npm = $("#field_npm").val();
            addFriend(name, npm);
            event.preventDefault();
        });

        $("#field_npm").change(function () {
            console.log($(this).val());
            npm = $(this).val();
            $.ajax({
                method: "POST",
                url: '{% url "lab-7:validate-npm" %}',
                data: {
                    'npm': npm
                },
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    if (data.is_taken) {
                        alert("Mahasiswa dengan npm seperti ini sudah ada");
                    }
                }
            });
        });


        var getFriendDescription = function (id) {
            console.log(id);
            window.open('friend-description/' + id + '/', '_self');
        };
    </script>
{% endblock %}